### ISSUE TITLE
go modules conflict with version 0.19.0

### ISSUE THREAD

**Issue by sfro** [kubernetes/client-go#866] opened 2020-09-08 10:54 UTC
I am getting the following issue with `go mod tidy` when trying to use `https://github.com/kubernetes/client-go`.

```
<my project> imports
	k8s.io/client-go/kubernetes imports
	k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1 imports
	k8s.io/api/auditregistration/v1alpha1: module k8s.io/api@latest found (v0.19.0), but does not contain package k8s.io/api/auditregistration/v1alpha1
```

**Comment by liggitt** [comment] 2020-09-08 11:10
This is a duplicate of https://github.com/kubernetes/client-go/issues/862

Make sure you are using a consistent version of k8s.io/api, apimachinery, and client-go

**Closed by liggitt** 2020-09-08 11:10 UTC

**Comment by sfro** [comment] 2020-09-08 11:31
What version should client-go have? I'm seeing this in my go.mod file:
`k8s.io/client-go v11.0.0+incompatible`

Is version 11 the one I should have?

**Comment by liggitt** [comment] 2020-09-08 12:12
`v0.19.0` is the latest release of all the modules

**Comment by sfro** [comment] 2020-09-08 12:38
Ok, I guess I'm just extremely confused over all the version tags for the different projects
