### ISSUE TITLE
error running compiler

### ISSUE THREAD

**Issue by snxq** [kubernetes/client-go#598] opened 2019-04-24 03:39 UTC
https://github.com/kubernetes/client-go/blob/6ee68ca5fd8355d024d02f9db0b3b667e8357a0f/rest/request.go#L598

```
compile: error running compiler: exit status 2
/root/.cache/bazel/_bazel_root/9fb8753853fa4f06dcf18e6226b8e4f5/execroot/__main__/vendor/k8s.io/client-go/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

Is this my method wrong?

**Comment by liggitt** [comment] 2019-04-24 03:42
Duplicate of https://github.com/kubernetes/client-go/issues/584

Be sure you are using the tagged version of k8s.io/apimachinery which corresponds to the version of client-go you are using

/close

**Closed by liggitt** 2019-04-24 03:42 UTC

**Comment by snxq** [comment] 2019-04-24 03:53
OK. I got the reason.

Thanks.
