### ISSUE TITLE
Introduce Go Modules

### ISSUE THREAD

**Issue by marwan-at-work** [kubernetes/client-go#455] opened 2018-08-26 21:31 UTC
With Go 1.11 released, it would be great to lock the dependencies of client-go users through a go.mod file. 

I'm not totally familiar with how kubernetes/kubernetes/staging and kubernetes/client-go get synchronized. So I didn't open a PR. 

However, I did write a [tool](https://github.com/marwan-at-work/mod) to help migrate >=2 repos to Semantic Import Versioning I applied those imports to the client-go repository directly: https://github.com/marwan-at-work/client-go/commit/47880e79b47d26f3f4f9b619946d9e7b84787982

**Comment by liggitt** [comment] 2018-08-26 21:33
Thanks for the issue. Closing as a dupe of https://github.com/kubernetes/kubernetes/issues/63607 as we need to determine a coherent strategy for supporting go modules for the whole project. 

/close

**Closed by liggitt** 2018-08-26 21:33 UTC
