### ISSUE TITLE
Watch channel does not get closed ever

### ISSUE THREAD

**Issue by hardikdr** [kubernetes/client-go#755] opened 2020-02-26 12:12 UTC
## Problem Description
The watch appears to stop receiving the events for certain custom-resources. This leads to stale-cache reads, but the watch is not re-established.

### What is expected?
We expect the following client log message to be seen after every timeout minutes[~10mins],
`I0226 11:09:10.181906       1 reflector.go:405] sample-controller/pkg/client/informers/externalversions/factory.go:117: Watch close - *v1alpha1.Flunder total 0 items received`

From basic investigation, it seems [`watchHandler`](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L393) could technically loop forever if [`ResultChan`](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L436) is hung or never closed from servere-side. This could happen if watch is closed from APIServer and the client isn't aware, not sure how and why. There does not seem to be a timeout from client side. If the server closes the connection but the client is missing it then it could get hung forever? (See also: https://stackoverflow.com/questions/51399407/watch-in-k8s-golang-api-watches-and-get-events-but-after-sometime-doesnt-get-an)
- We see this happening often with our GKE clusters, where custom-controllers stops getting events and leads to stale-cache reads after some time. Though, this only started recently without us upgrading GKE or upgrading the custom controllers.
 
Any help will be really appreciated, thanks in advance.

**Comment by liggitt** [comment] 2020-02-26 12:36
What version of the API server are you running against? They were known issues related to this that were fixed in 1.15

**Comment by hardikdr** [comment] 2020-02-26 12:40
We are running 1.14.8-gke.33 . 
Can you please point to any issue/PR for the problem you are referring to?

**Comment by liggitt** [comment] 2020-02-26 12:53
The issue was fixed in https://github.com/kubernetes/kubernetes/pull/78029 and the associated bugs are linked from that

**Closed by liggitt** 2020-02-26 12:53 UTC

**Comment by rfranzke** [comment] 2020-02-26 13:11
Thanks for pointing this out @liggit, 💯 
One question - I saw you cherry-picked this fix to the `release-1.14` branch with https://github.com/kubernetes/kubernetes/pull/78034 end of May 2019. However, looking at the respective commit https://github.com/kubernetes/kubernetes/pull/78034/commits/21b9a31c3308c1f4c0e3b5492fbe0301f2bfeaf7 it looks like it never was released in a hotfix of 1.14 - how is that possible? The last 1.14 version 
was [1.14.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.14.10) released in December 2019. Shouldn't it be included here?

**Comment by rfranzke** [comment] 2020-02-26 13:15
I checked the release notes and from here it seems that it was released with `v1.14.3` (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#changelog-since-v1142), not sure why the GitHub commit is not showing it.
Can you explain why we are still hit by it although we are running `v1.14.8`?

**Comment by liggitt** [comment] 2020-02-26 13:37
I'm not sure. Starting a 1.14.8 cluster and starting a watch with timeoutSeconds set is closing the connection and exiting the watch as I would expect.

**Comment by rfranzke** [comment] 2020-02-26 13:42
Hm, should we then rather reopen this issue? Any other hints what it might be?
What @hardikdr describes is only observed after some time, it doesn’t happen immediately. We also don’t know yet how to exactly reproduce it.

**Comment by liggitt** [comment] 2020-02-26 13:45
The client-side code closes the channel as soon as the server closes the connection, so this issue likely doesn't belong in this repo. If you want to open an issue against https://github.com/kubernetes/kubernetes/issues/, you can, though it would need to be reproduced against a maintained OSS branch (currently 1.15+). More information about what you are doing/seeing would be helpful as well:

* client code used to set up the informer (including configured timeouts, etc)
* what other activity is happening to the relevant CRD and custom resource instances before/while the watch is open

**Comment by hardikdr** [comment] 2020-02-26 14:20
>client code used to set up the informer (including configured timeouts, etc)

Resync-period is set to 12hrs, and timeout is not set explicitly, defaulted.

>what other activity is happening to the relevant CRD and custom resource instances before/while the watch is open

Definitions are re-applied by the controller but not necessarily changed, not in a regular fashion. Custom resource instances are updated regularly when the watch is open.

We see below log-lines regularly for a custom-resource but it stops after sometime when the watch is hung I believe. 
`I0226 06:36:51.828470       1 reflector.go:405] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.Flunder total 30 items received`

[Ref](https://github.com/gardener/machine-controller-manager/blob/master/cmd/machine-controller-manager/app/controllermanager.go#L231-L236) to the actual implementation.

**Comment by amshuman-kr** [comment] 2020-02-27 08:42
Ideally, the client-side should implement the timeout by itself without depending on the server side to close the channel on timeout. This has already been done [recently in client-go](https://github.com/kubernetes/client-go/commit/ae9f6b2601c8f8b97ad2865943f423d65539ffdb#diff-cce82935c007206a9e6070b09220908bR559) but not released yet. We should adopt this change as soon as it is released to insulate ourselves from such issues in the future.

**Comment by amshuman-kr** [comment] 2020-03-06 09:50
> the CR-specific issues were resolved in 1.15 (and picked back to 1.12.9, 1.13.7, 1.14.3), but there are more systemic issues that can occur at the client transport level if the underlying tcp connection is disrupted but not disconnected (like #374)

Won't using client-side timeout (now that it has been [made possible](https://github.com/kubernetes/client-go/commit/ae9f6b2601c8f8b97ad2865943f423d65539ffdb#diff-cce82935c007206a9e6070b09220908bR559)) be the right way to reliably refresh buggy listen connections?
