### ISSUE TITLE
cannot convert klog.V(9) (type klog.Verbose) to type bool

### ISSUE THREAD

**Issue by prestonvanloon** [kubernetes/client-go#659] opened 2019-08-16 18:51 UTC
This is failing with `go get`. 
```
# k8s.io/client-go/transport
../../../k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
# k8s.io/utils/trace
../../../k8s.io/utils/trace/trace.go:100:57: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
../../../k8s.io/utils/trace/trace.go:112:56: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
```

**Comment by liggitt** [comment] 2019-08-16 18:55
This is a duplicate of https://github.com/kubernetes/client-go/issues/656#issuecomment-521869630

 The log library was just changed in the last day on the master branch. You will need to use a compatible tag of that library in your build

**Closed by liggitt** 2019-08-16 18:55 UTC

**Comment by prestonvanloon** [comment] 2019-08-16 18:57
Is there any plan to fix it? Some pipelines may not have gomodules support so they are broken from this.

**Comment by liggitt** [comment] 2019-08-16 19:16
eventually either the klog PR will be reworked or it will be pulled into k8s.io/kubernetes and a compatible version of k8s.io/client-go will be published to master, but I'd recommend avoiding a pipeline that relies on master of all transitive dependencies.

**Comment by rsreeni** [comment] 2019-09-10 14:44
Hi,

Im still having the issue.. 

Heres the error I get

src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool

src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool

src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool

src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool


My go.mod refers as follows..


                istio.io/api v0.0.0-20190907133855-07957a9b3cc0

                k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d

                k8s.io/client-go v0.0.0-20190819141724-e14f31a72a77

                k8s.io/klog v0.4.0 // indirect

                k8s.io/kube-openapi v0.0.0-20190816220812-743ec37842bf // indirect

                k8s.io/utils v0.0.0-20190907131718-3d4f5b7dea0b // indirect


Any help on what I am doing wrong ? Stuck with a broken build now.

Thanks,

-Sreeni

**Comment by lebinhe** [comment] 2019-09-19 03:47
replace klog.V(...) with klog.V(...).Enabled()

**Comment by piyushkv1** [comment] 2019-11-15 18:59
@lebinhe lebinhe Can we merge this patch of adding Enabled()
