### ISSUE TITLE
Go get fails with go 1.13

### ISSUE THREAD

**Issue by jaloren** [kubernetes/client-go#670] opened 2019-09-05 21:17 UTC
1. install go 1.13 on your system
2. cd into a directory that is a go module
3.  now run go get
```
go get k8s.io/client-go@v12.0.0
go: finding k8s.io/client-go v12.0.0
go get k8s.io/client-go@v12.0.0: k8s.io/client-go@v12.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v12
```

The issue is that semantic import versioning requires the module declaration to be:

```
module k8s.io/client-go/v12
```

**Comment by nikhita** [comment] 2019-09-06 06:51
Kubernetes only supports go 1.12 for now. It's a known issue that there are several problems with 1.13, see https://github.com/kubernetes/kubernetes/issues/78845#issuecomment-501447560 for more details.

Closing in favour of https://github.com/kubernetes/kubernetes/issues/78845
/close

**Closed by nikhita** 2019-09-06 06:51 UTC

**Comment by BenTheElder** [comment] 2019-09-10 01:39
noting that `v11.0.0` will work, but not `v12`+ due to the go.mod added here

**Comment by liggitt** [comment] 2019-09-10 01:48
also updated the install instructions with non-semver tags that will work (even if they resolve to v0.0.0 pseudo versions), rather than complain about non-semantic-import-versioning module names

**Comment by carnott-snap** [comment] 2019-09-16 18:36
@jaloren, there is a workaround I found, though it will cause various parts of the go1.13 toolchain to emit logging or errors, signalling that this could just be a bug:

It appears that while `go get` does not work, a manually curated `go.mod` file works fine:
```go
module test
  
go 1.13

require k8s.io/client-go v12.0.0+incompatible
```
```go
package main
  
import (
        "fmt"

        "k8s.io/client-go/pkg/version"
)

func main() { fmt.Println(version.Get()) }
```
```sh
[user@localhost test]$ go run .
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
v0.0.0-master+$Format:%h$
[user@localhost test]$ go build
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
[user@localhost test]$ ./test 
v0.0.0-master+$Format:%h$
[user@localhost test]$ go doc k8s.io/client-go/pkg/version
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
go list -m: k8s.io/client-go@v12.0.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
package version // import "k8s.io/client-go/pkg/version"

Package version supplies version information collected at build time to
kubernetes components.

func Get() apimachineryversion.Info
```

**Comment by liggitt** [comment] 2019-09-16 18:38
it's not a bug, go1.13 go stricter about allowing using semver tags >= 2.0 with go modules that did not end with a `/v<N>` suffix. Using the non-semver tags with go get (see INSTALL.md instructions) works around the issue for now. We're considering how best to support semantic import versioning in these repose.

**Comment by carnott-snap** [comment] 2019-09-16 20:01
Sorry if I was unclear. I am familiar with the module [version validation](https://golang.org/doc/go1.13#version-validation) changes in go1.13. The potential bug I am referring to is that `go get` does this validation, but other parts of the toolchain do not, see golang/go#34330.

**Comment by liggitt** [comment] 2019-09-16 20:35
> The potential bug I am referring to is that `go get` does this validation, but other parts of the toolchain do not, see [golang/go#34330](https://github.com/golang/go/issues/34330).

oh, got it. I would probably assume that is a bug that will be fixed. Until semantic import versioning is implemented in kubernetes, I'd probably recommend using the `kubernetes-1.x.y` tags instead.

**Comment by liggitt** [comment] 2019-11-11 22:34
update:
* go1.13 support landed in master in https://github.com/kubernetes/kubernetes/pull/82809
* we plan to add v0.x.y tags to published repositories like `k8s.io/{client-go,api,apimachinery}` where x and y correspond to Kubernetes v1.x.y, so go.mod will preserve tag info instead of `v0.0.0-$date-$sha` (see https://github.com/kubernetes/enhancements/pull/1350 ... hopefully in time for 1.17.0, but possibly for 1.18.x)

**Comment by cute-angelia** [comment] 2020-03-04 07:15
```
replace k8s.io/client-go => k8s.io/client-go v12.0.0+incompatible
```

**Comment by jonas27** [comment] 2020-04-07 10:24
for me it was version v0.18.0 that worked, ie
_k8s.io/client-go v0.18.0_
that was also the version the k8s.io/api was at anyway

**Comment by ultra-baba** [comment] 2021-06-24 05:58
> ```
> replace k8s.io/client-go => k8s.io/client-go v12.0.0+incompatible
> ```

why?
