### ISSUE TITLE
Using for ThirdPartyResource's

### ISSUE THREAD

**Issue by tiaanl** [kubernetes/client-go#8] opened 2016-10-06 12:18 UTC
I've started using this library and it works very well.

When extending the API with ThirdPartyResource resources, things become a major issue.  Using the dynamic part doesn't work well because I don't want to convert all my objects into map[string]interface{} objects.  The rest part alone also doesn't work well, because there are no Encoders/Decoders.

I'm sure all the tools required to start working with my own resources is available, but get them all up and running is just a major pain point currently.

Right now I don't know enough of the internals to be productive towards a solution, but any solution would be MUCH appreciated.

**Comment by lavalamp** [comment] 2016-10-06 19:11
@smarterclayton @krousey Do we have a convenient go struct <-> TPR codec laying around somewhere?

**Comment by tiaanl** [comment] 2016-10-07 09:29
Okay, so I've made progress on my side.  Using the `rest` part of the library is quite useful, but the biggest problem is still plenty of little details that is not really reported when not done correctly.

Doing a `GET` for a list of objects you need the following `into` object:

```go
type ProjectList struct {
	unversioned.TypeMeta `json:",inline"`
	unversioned.ListMeta `json:"metadata,omitempty"`

	Items []Project `json:"items"`
}
```

Notice the `unversioned.ListMeta` here.  Without it, you will just not get the right result or something like `not a registered type`.  Very confusing.

The final issue I have here still is that when I try to pull that same list with this call:

```go
type ProjectSpec struct {
	Description string `json:"description"`
}

type Project struct {
	unversioned.TypeMeta `json:",inline"`
	api.ObjectMeta        `json:"metadata,omitempty"`

	Spec ProjectSpec `json:"spec"`
}


	projectList := ProjectList{}
	err := ah.Client.Rest.Get().
		Namespace("default").
		Resource("projects").
		Do().
		Into(&projectList)
```

The list object gets the right details, but the actual items do not.  They are just blank with no data.  I've figured out that it is the ObjectMeta type that is causing this error.  If I recreate my own ObjectMeta struct, then it works perfectly.  So I think there is another *interface-detecting* mechanism somewhere in the decoding that doesn't like the ObjectMeta type.

If I get all of this to work, I would definitely like to write a doc for how to use all this.

**Comment by deads2k** [comment] 2016-10-07 12:13
> The list object gets the right details, but the actual items do not. They are just blank with no data. I've figured out that it is the ObjectMeta type that is causing this error. If I recreate my own ObjectMeta struct, then it works perfectly. So I think there is another interface-detecting mechanism somewhere in the decoding that doesn't like the ObjectMeta type.

You might be getting bit by ugorji codec generation.  We had a problem with it downstream that we resolved by carrying a patch that deleted the generated codecs until we generated them for our types.

Also, if you're using third party resources, make sure you're aware of the known issues/missing features: https://github.com/kubernetes/features/issues/95

**Comment by justinsb** [comment] 2016-10-09 15:21
I hit the same thing, and copying ObjectMeta into my package fixes the problem.

Do we know why this happens?  Is there an issue tracking this @deads2k?

**Comment by deads2k** [comment] 2016-10-10 11:37
> Do we know why this happens? Is there an issue tracking this @deads2k?

I think it's because there's an interface check that passes because the object is anonymously included, but I haven't dug into this case to make sure.  I don't know of an issue.  We discovered it in OpenShift and didn't think it was reasonable to try to force reversion or object shape change to accommodate it.  I think we fixed the correctness problems in the codec generator, so it ought to be safe to use for generating a codec now.

**Comment by lavalamp** [comment] 2016-10-10 16:48
It's ugorji--either run ugorji to generate en/decoders for your types, or
add a top level Decode() (double check the name) method that calls the
default json machinery.

**Comment by wfarr** [comment] 2016-10-21 14:13
> add a top level Decode() (double check the name) method that calls the default json machinery

I'm encountering similar issues to others in this issue.

Please excuse my ignorance here. I'm playing catch-up on the internals of this repository still. Would you be able to point me towards what the `Decode()` method should be added to? Is it my custom types being passed to `Into()`?

I can also publish some of the code that I've been working on for our use case publicly to demonstrate what I'm doing (or more likely doing wrong 😉 ) if context is lacking (that said, my work is modeled pretty closely after what I've read from others here in this issue).

**Comment by caesarxuchao** [comment] 2016-10-21 21:34
> Would you be able to point me towards what the Decode() method should be added to? Is it my custom types being passed to Into()?

Yes.

Or you can take a look at this [file](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.generated.go), which is the generated ugorji code in the k8s repository, you can generate similar code for your types. The code is generated using this [script](https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh#L147). (I think write your own Decode() is easier, k8s uses ugorji because it's more efficient than the default json package).

**Comment by caesarxuchao** [comment] 2016-10-27 21:11
Paste the slack discussion here since it might be useful for other people.

As ugorji [doc](http://ugorji.net/blog/go-codec-primer) says:
"if value implements encoding.TextUnmarshaler and format is a text format, call its UnmarshalText method"

So you need to implement the [UnmarshalText()](https://github.com/golang/go/blob/master/src/encoding/encoding.go#L46-L48) method for your type, you can use json.Unmarshal to implement it. For example:
```go
type YourType struct {
}

func (yourType *YourType) UnmarshalText(data []byte) error {
  return  json.Unmarshal(data, yourType)
}
```

**Comment by tiaanl** [comment] 2016-10-30 21:29
I created a repo to test just accessing the third party resources.

https://github.com/tiaanl/kube-tpr-demo

It has a few simple comands to interact with k8s.

The first issue with using the dynamic package is solved by registering my types with `api.Schema`.

The only last issue is still the decoding of the json into the correct types.  Ive tried all the recommendations in this thread, except for generating that huge file for my type, which tbh is entirely overkill for trying to create something this simple.

Being able to store your meta data inside k8s, using the api versioning and all the other benefits you get for free would be fantastic.  No more separate etcd with boilerplate code you have to write yourself.

Any help on this issue would be greatly appreciated.

**Comment by caesarxuchao** [comment] 2016-10-30 22:08
@tiaanl I heard the `UnmarshalText` method I pasted above didn't work. I'll debug it these days and report back here, since it's blocking so many people.

**Comment by wfarr** [comment] 2016-10-30 22:10
Thanks so much! I know the indirection and back-and-forth can be really
frustrating and time consuming. I appreciate your attention and effort
towards helping suss these issues out. ❤️

**Comment by caesarxuchao** [comment] 2016-10-31 02:03
Finally got it work. See "Problem 1" and "Problem 2" in the code: See https://github.com/wfarr/k8s-tpr-playground/pull/1.

**Comment by caesarxuchao** [comment] 2016-10-31 02:15
Reported issue https://github.com/ugorji/go/issues/178

**Comment by wfarr** [comment] 2016-10-31 14:16
I can definitely confirm these work-arounds are functional. 👍 

The serialization _mostly_ seems to work with `cache.NewInformer()` as well (something we expect to use). I've pushed up some code demonstrating this at https://github.com/wfarr/k8s-tpr-playground/blob/master/main_test.go#L36-L86

The current reflector errors with `cache.NewInformer()` on TPRs:

```
E1031 10:11:23.642558   66896 reflector.go:214] github.com/wfarr/k8s-tpr-playground/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Unable to understand list result &main.ExampleList{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, Metadata:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Items:[]main.Example{main.Example{TypeMeta:unversioned.TypeMeta{Kind:"Example", APIVersion:"wfarr.systems/v1"}, Metadata:api.ObjectMeta{Name:"example1", GenerateName:"", Namespace:"default", SelfLink:"/apis/wfarr.systems/v1/namespaces/default/examples/example1", UID:"ca182ddf-9d1e-11e6-9df1-42010af0008b", ResourceVersion:"3644329", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63613263424, nsec:0, loc:(*time.Location)(0x13236e0)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"example1\",\"namespace\":\"default\",\"creationTimestamp\":null},\"data\":\"eyJhcGlWZXJzaW9uIjoid2ZhcnIuc3lzdGVtcy92MSIsImtpbmQiOiJFeGFtcGxlIiwibWV0YWRhdGEiOnsibmFtZSI6ImV4YW1wbGUxIn0sInNwZWMiOnsiYmFyIjp0cnVlLCJmb28iOiJIZWxsbyJ9fQ==\"}"}, OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:main.ExampleSpec{Foo:"Hello", Bar:true}}}}: object does not implement the List interfaces
```

Of note, the contained `[]Example` as `*ExampleList.Items` is deserialized perfectly, so it just seems to be unhappy with the `TypeMeta` or `ListMeta` on `*ExampleList` itself blowing up right now? I've poked around at a few attempts at fixing this (and will keep doing so), but any guidance on this would be much appreciated.

**Comment by wfarr** [comment] 2016-11-03 20:10
Good news!

I was able to get `cache.NewInformer()` working with this stuff by performing similar workarounds against my ExampleList type.

Namely:

* Stopped embedding the ListMeta
* Added `GetListMeta()` to satisfy the List interface

https://github.com/wfarr/k8s-tpr-playground/commit/3b0d1439719da3527e23f32ab4624e72aa991c92#diff-7ddfb3e035b42cd70649cc33393fe32c demonstrates a working example

**Comment by caesarxuchao** [comment] 2016-11-03 20:18
That's very cool!

**Comment by smarterclayton** [comment] 2016-11-04 05:23
We are going to nuke ugorji in 1.6 (now that we have protobuf support) and
that will get around the problem mentioned above of having to implement the
deserializer.

**Comment by rmohr** [comment] 2016-11-07 12:27
@caesarxuchao @wfarr thx for your examples. Can also  confirm that #29 works.

**Comment by caesarxuchao** [comment] 2016-11-21 22:30
Thanks @rmohr for the confirmation. The example got merged.

**Closed by caesarxuchao** 2016-11-21 22:30 UTC

**Comment by hongchaodeng** [comment] 2017-02-14 17:35
@caesarxuchao 

I don't think this is fixed. Users of TPR client still have the problem. When defining types, they need to understand the workarounds and put them in their code. But there isn't any docs for it. There isn't any easy way for user to write a TPR client either.

Can we keep this open? Or shall we open another to track the issue?

**Comment by nilebox** [comment] 2017-03-09 12:01
Just had the same problem both with `2.0.0` and `master` revisions, and found two workarounds (both work).

> If I recreate my own ObjectMeta struct, then it works perfectly. So I think there is another _interface-detecting_ mechanism somewhere in the decoding that doesn't like the ObjectMeta type.

Indeed, some implicit interface seems to be the root cause of the issue. So the workarounds are:

1. Create _own copy_ of **ObjectMeta type** and use it instead of the one provided by client-go. Seems boilerplaty, and we still need this type to implement ObjectMetaAccessor interface:
```
// Required to satisfy ObjectMetaAccessor interface
func (e *Example) GetObjectMeta() metav1.Object {
	return &e.Metadata
}
```
So you will have to manually create a copy of this object to satisfy the interface.

2. Just _rename_ the **ObjectMeta field** to _anything different_, for example call it Metadata. It just works. 

> We are going to nuke ugorji in 1.6 (now that we have protobuf support) 

Great news! Debugging problems like this one is not fun.

**Comment by nilebox** [comment] 2017-03-09 21:59
@caesarxuchao Yes, I saw this example, and it should work (since you explicitly called a field **Metadata**). But since there are no comments around it, I didn't expect the naming is important here.

So I created my type based on the Kubernetes [Deployment type](https://github.com/kubernetes/client-go/blob/master/pkg/apis/extensions/types.go#L165) which has an **ObjectMeta** field. So I ran into problem tracked in this issue, and renaming the field solved it.

I would suggest to add some comment or link to this issue to your example so newcomers would pay attention to it.
