### ISSUE TITLE
How to add context in the request?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/client-go#291] opened 2017-09-08 03:20 UTC
I think add context in the request cloud help in tracing system as well as early cancel, is there a support for `golang.org/x/net/context` ?

**Comment by maleck13** [comment] 2017-10-05 13:50
I believe this issue is related to what you are referring to https://github.com/kubernetes/kubernetes/issues/46503

**Comment by sttts** [comment] 2018-02-12 07:34
duplicate of https://github.com/kubernetes/kubernetes/issues/46503
/close

**Closed by sttts** 2018-02-12 07:34 UTC
Labels: lifecycle/rotten
