### ISSUE TITLE
transport: compile time error

### ISSUE THREAD

**Issue by gbbr** [kubernetes/client-go#658] opened 2019-08-16 10:02 UTC
The client-go package can no longer be installed:
```
$ go test ./transport
# k8s.io/client-go/transport [k8s.io/client-go/transport.test]
transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
FAIL	k8s.io/client-go/transport [build failed]
```
It's a really weird one, not sure how it came to be. Those lines of code haven't been touched in 9 months but it doesn't make sense to convert a `struct` to a `bool`.

Change was introduced in https://github.com/kubernetes/klog/pull/20

**Comment by liggitt** [comment] 2019-08-16 12:40
This is a duplicate of https://github.com/kubernetes/client-go/issues/656#issuecomment-521869630

 The log library was just changed in the last day on the master branch. You will need to use a compatible tag of that library in your build

**Closed by liggitt** 2019-08-16 12:40 UTC
