### ISSUE TITLE
Object's TypeMeta is empty

### ISSUE THREAD

**Issue by mickael-carl** [kubernetes/client-go#413] opened 2018-05-19 00:33 UTC
Running the following:

```
package main

import (
    "log"

    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/client-go/kubernetes"
    "k8s.io/client-go/tools/clientcmd"
    _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)   
    
func main() {
    config, err := clientcmd.BuildConfigFromFlags("", "/home/carlm/.kube/config")
    clientset, err := kubernetes.NewForConfig(config) 
    
    configMaps, err := clientset.CoreV1().ConfigMaps("some-namespace").List(metav1.ListOptions{})
    log.Print(configMaps.Items[0].TypeMeta)
    log.Print(configMaps.TypeMeta)
}   
```

should yield non-empty TypeMetas but actually yields nothing in both cases ("{ }"). I believe this has also been mentioned [here](https://github.com/kubernetes/client-go/issues/193#issuecomment-383535861).

**Comment by liggitt** [comment] 2018-05-19 00:44
Reported in https://github.com/kubernetes/kubernetes/issues/3030

Fix in progress in https://github.com/kubernetes/kubernetes/pull/63972

**Comment by nikhita** [comment] 2018-06-24 16:47
Dupe of https://github.com/kubernetes/client-go/issues/308

**Comment by mickael-carl** [comment] 2018-06-29 09:21
Thanks for pointing it out!

**Closed** 2018-06-29 09:20 UTC
