### ISSUE TITLE
Bundling k8s client-go includes internal packages

### ISSUE THREAD

**Issue by ideahitme** [kubernetes/client-go#38] opened 2016-11-14 21:28 UTC
Trying to bundle k8s client-go with godep throws the following error:
```

        imports k8s.io/client-go/kubernetes
	imports k8s.io/client-go/discovery
	imports k8s.io/client-go/pkg/api
	imports k8s.io/client-go/pkg/api/meta
	imports k8s.io/client-go/pkg/api/unversioned
	imports github.com/go-openapi/spec
	imports github.com/go-openapi/jsonreference
	imports github.com/PuerkitoBio/purell
	imports golang.org/x/text/secure/precis
	imports golang.org/x/text/cases
	imports golang.org/x/text/internal
	imports golang.org/x/text/language
	imports golang.org/x/text/internal/tag
```

**Comment by caesarxuchao** [comment] 2016-11-21 22:36
What's the error message?

**Comment by WilliamDenniss** [comment] 2017-03-15 00:46
Closing as Unable to Reproduce. Please re-open with more information if you're still having this issue.

**Closed** 2017-03-15 00:46 UTC
Labels: question
