### ISSUE TITLE
undefined: v1.FinalizerOrphan

### ISSUE THREAD

**Issue by H22F** [kubernetes/client-go#93] opened 2017-02-07 08:00 UTC
I get the go get k8s.io/client-go/1.5/...
An error occurred while trying to go run:

> # k8s.io/client-go/pkg/api/v1
> ../k8s.io/client-go/pkg/api/v1/helpers.go:86: undefined: v1.FinalizerOrphan

Want to how to deal with, please?

**Comment by H22F** [comment] 2017-02-07 08:29
../k8s.io/client-go/pkg/api/v1/helpers.go:86:

```
var standardFinalizers = sets.NewString(
	string(FinalizerKubernetes),
	metav1.FinalizerOrphan,
)
```

**Comment by kmhagan** [comment] 2017-02-07 19:20
I am receiving the same error when trying to run the in cluster example:
client-go/examples/in-cluster/main.go

**Comment by BroganD1993** [comment] 2017-02-07 22:54
Me too, does anyone know what could be causing this?

**Comment by anshumanbh** [comment] 2017-02-07 23:24
I get the same error while trying to run an out-of-cluster config in minikube locally. This used to work just fine. Not sure what happened or how to fix this error?

**Comment by floreks** [comment] 2017-02-08 12:20
It seems to be caused by latest bot publish update. 

This is client-go vendored version of apimachinery: https://github.com/kubernetes/client-go/blob/master/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go

This is latest version which contains this finalizer: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L75

You have to wait for the fix or try to manually update vendor deps of client-go.

**Comment by caesarxuchao** [comment] 2017-02-10 07:32
@H22F, it's happening in the master branch, right? What @floreks said is correct. I'm going to push a fix to the master branch and then suspend the bot, until the bot have CI tests.

**Comment by H22F** [comment] 2017-02-10 07:36
@caesarxuchao yes,happening in the master branch . 
Now master branch is fix?

**Comment by caesarxuchao** [comment] 2017-02-10 13:04
Not yet. I'm waiting for the k8s.io/apimachinery to be synced first, then I can fix client-go. I'll keep an eye on it this weekend. The entire publishing process is complicated by the dependencies among multiple repos, sorry. We are actively working on improving the publishing process and the stability of client-go.

**Comment by H22F** [comment] 2017-02-10 14:16
@caesarxuchao OK,Please fix after notice.Thanks

**Comment by ideahitme** [comment] 2017-02-12 21:40
yes, seems last stable commit is at 1679e38db83a0dbe1ef86deab577eead47ce75e2

**Comment by caesarxuchao** [comment] 2017-02-13 04:06
Master should be fixed now. Please let me know if it's not.

**Closed** 2017-02-13 04:05 UTC
