### ISSUE TITLE
kubectl 1.18.0 adds "spn" to azure apiserver-id all the time ...

### ISSUE THREAD

**Issue by sybnex** [kubernetes/client-go#779] opened 2020-04-06 05:24 UTC
Since I'm using kubectl in the new version it add for every kubectl execution the string "spn:" to the field of apiserver-id. 

After several requests you won't be able to connect to the AKS api anymore with the error:
kubectl version
```
E0406 07:12:30.769683    5213 azure.go:154] Failed to acquire a token: refreshing the expired token: refreshing token: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named spn:spn:spn:spn:spn:spn:spn:spn:spn:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx was not found in the tenant named xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nCorrelation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nTimestamp: 2020-04-06 05:12:30Z","error_codes":[500011],"timestamp":"2020-04-06 05:12:30Z","trace_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","correlation_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","error_uri":"https://login.microsoftonline.com/error?code=500011"}
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

The .kube/config looks like:
```
...
        apiserver-id: spn:spn:spn:spn:spn:spn:spn:spn:spn:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        config-mode: "0"
        environment: AzurePublicCloud
...
```

Workaround: Delete all the "spn:" in the config file ... or downgrade to kubectl an older version.

**Comment by liggitt** [comment] 2020-04-06 07:22
Thanks for the report. This is a duplicate of https://github.com/kubernetes/kubernetes/issues/89672 and will be fixed in 1.18.1

**Closed by liggitt** 2020-04-06 07:22 UTC
